import { IsString, Matches } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

// #412 — expose the login request body as a named DTO so the OpenAPI
// document generated by @nestjs/swagger includes the schema and field
// descriptions. class-validator decorators were already present on the
// inline class; only @ApiProperty annotations are added here.

export class WalletLoginDto {
  @ApiProperty({
    description: 'Stellar wallet address (G...)',
    example: 'GAHJJJKMOKYE4RVPZEWZTKH5FVI4PA3VL7GK2LFNUBSGBKQTRB7KXQZ',
  })
  @IsString()
  @Matches(/^G[A-Z2-7]{55}$/, { message: 'Invalid Stellar wallet address' })
  walletAddress: string;

  @ApiProperty({
    description: 'Base64-encoded Ed25519 signature of the challenge message',
    example: 'YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=',
  })
  @IsString()
  signature: string;

  @ApiProperty({
    description: 'The nonce string obtained from GET /auth/challenge',
    example: 'a3f1c2d4e5b6...',
  })
  @IsString()
  message: string;
}
